# Generated by Django 2.1.2 on 2018-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='customers',
            table='customer',
        ),
    ]
