# Generated by Django 2.1.2 on 2018-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customers_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='temp_id',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
