# Generated by Django 2.1.2 on 2018-10-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20181010_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='temp_id',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
