# Generated by Django 2.1.2 on 2018-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20181010_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
