# Generated by Django 2.1.2 on 2018-10-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customers_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='activated',
            new_name='is_active',
        ),
    ]
