# Generated by Django 2.1.2 on 2018-10-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20181010_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='mobile',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
