# Generated by Django 2.1.2 on 2018-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customers_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
    ]
