# Generated by Django 2.1.2 on 2018-10-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.FileField(default='static/customer/profile/default.png', upload_to='static/customer/profile'),
        ),
    ]
