# Generated by Django 2.1.2 on 2018-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20181013_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=500),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default='000000'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='street', max_length=500),
            preserve_default=False,
        ),
    ]
