# Generated by Django 2.1.2 on 2018-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20181022_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='wow', max_length=500),
            preserve_default=False,
        ),
    ]
