# Generated by Django 2.1.2 on 2018-11-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
