# Generated by Django 2.1.2 on 2018-11-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_customers_is_b2b'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForB2B',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_responsed', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
            ],
            options={
                'db_table': 'request_for_b2b',
            },
        ),
    ]
