# Generated by Django 2.1.2 on 2018-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_requestforb2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
