# Generated by Django 2.1.2 on 2018-11-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=16)),
                ('is_applied', models.BooleanField(default=False)),
                ('price_value', models.FloatField()),
            ],
            options={
                'db_table': 'coupon_code',
            },
        ),
    ]
