# Generated by Django 2.1.2 on 2018-11-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcodes',
            old_name='price_value',
            new_name='discount_percentage',
        ),
    ]
