# Generated by Django 2.1.2 on 2018-11-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0017_address_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=10)),
                ('txnid', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('productinfo', models.TextField()),
                ('hash', models.TextField()),
                ('error', models.TextField()),
                ('pg_type', models.CharField(max_length=11)),
                ('bank_ref_num', models.CharField(max_length=21)),
                ('mihpayid', models.TextField()),
                ('card_category', models.TextField()),
                ('discount', models.FloatField()),
                ('net_amount_debit', models.FloatField()),
                ('payment_source', models.TextField()),
                ('bank_code', models.TextField()),
                ('error_message', models.TextField()),
                ('card_num', models.CharField(max_length=20)),
                ('name_on_card', models.CharField(max_length=30)),
                ('cardhash', models.TextField()),
                ('issuing_bank', models.TextField()),
                ('card_type', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
