# Generated by Django 2.1.2 on 2018-10-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0014_auto_20181013_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('food_group', models.CharField(max_length=200)),
                ('no_of_portions', models.IntegerField()),
                ('use_of_goods', models.CharField(max_length=10)),
                ('ingredients', models.TextField(max_length=2000)),
                ('cooking_process_name', models.CharField(max_length=100)),
                ('cooking_process_method', models.TextField(max_length=2000)),
                ('tags', models.CharField(max_length=100)),
                ('is_apporved', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
