# Generated by Django 2.1.2 on 2018-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181013_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
