# Generated by Django 2.1.2 on 2018-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipes_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
