# Generated by Django 2.1.2 on 2018-10-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181013_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
