# Generated by Django 2.1.2 on 2018-11-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181013_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='picture_3',
        ),
        migrations.AddField(
            model_name='recipes',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
