# Generated by Django 2.1.2 on 2018-11-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_customers_is_admin'),
        ('blog', '0008_auto_20181110_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
