# Generated by Django 2.1.2 on 2018-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='temp_customer_id',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
