# Generated by Django 2.1.2 on 2018-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_temp_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='temp_customer_id',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
