# Generated by Django 2.1.2 on 2018-11-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
    ]
