# Generated by Django 2.1.2 on 2018-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('order_date', models.DateField(auto_now=True)),
                ('payment_mode', models.CharField(max_length=100)),
                ('is_payment_done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
