# Generated by Django 2.1.2 on 2018-11-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('customer', '0020_customers_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart_id', models.TextField()),
                ('total_price', models.FloatField()),
                ('order_date', models.DateField(auto_now=True)),
                ('payment_mode', models.CharField(max_length=100)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
