# Generated by Django 2.1.2 on 2018-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart_id1',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
