# Generated by Django 2.1.2 on 2018-11-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_cart_id1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart_id1',
        ),
    ]
