# Generated by Django 2.1.2 on 2018-10-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('storage', models.CharField(max_length=1000)),
                ('shelf_life', models.CharField(max_length=100)),
                ('uses', models.CharField(max_length=1000)),
                ('benefits', models.CharField(max_length=1000)),
                ('energy', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('suger', models.FloatField()),
                ('fat', models.FloatField()),
                ('ingridients', models.CharField(max_length=1000)),
                ('directions', models.CharField(max_length=1000)),
                ('picture_url', models.CharField(max_length=1000)),
                ('available_qty', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
