# Generated by Django 2.1.2 on 2018-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='products',
            name='picture_1',
            field=models.FileField(blank=True, upload_to='static/products/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='picture_2',
            field=models.FileField(blank=True, upload_to='static/products/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='picture_3',
            field=models.FileField(blank=True, upload_to='static/products/images'),
        ),
    ]
