# Generated by Django 2.1.2 on 2018-10-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181012_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='benefits',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='directions',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='ingridients',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='storage',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='uses',
            field=models.TextField(max_length=1000),
        ),
    ]
