# Generated by Django 2.1.2 on 2018-10-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181012_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
