# Generated by Django 2.1.2 on 2018-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_msg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_vegetarian',
            field=models.BooleanField(default=True),
        ),
    ]
