# Generated by Django 2.1.2 on 2018-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181012_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='wow', max_length=100),
            preserve_default=False,
        ),
    ]
