# Generated by Django 2.1.2 on 2018-10-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='suger',
            new_name='sugar',
        ),
    ]
