# Generated by Django 2.1.2 on 2018-11-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_b2b_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_msg',
            new_name='added_msg',
        ),
    ]
