# Generated by Django 2.1.2 on 2018-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181105_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='built_in_tenderizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='easy_to_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='egg_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='low_salt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='multi_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='three_in_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='added_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
