# Generated by Django 2.1.2 on 2018-11-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181110_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Bakery', 'Bakery'), ('Coating & Breading', 'Coating & Breading'), ('Staple Foods', 'Staple Foods'), ('Sauces, Pastes, Stock', 'Sauces, Pastes, Stock'), ('Seasonings & Marinades', 'Seasonings & Marinades')], default='Bakery', max_length=100),
        ),
    ]
