# Generated by Django 2.1.2 on 2018-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181110_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Bakery', 'Bakery'), ('Coating and Breading', 'Coating and Breading'), ('Staple Foods', 'Staple Foods'), ('Sauces, Pastes, Stock', 'Sauces, Pastes, Stock'), ('Seasonings and Marinades', 'Seasonings and Marinades')], default='Bakery', max_length=100),
        ),
    ]
